### PR TITLE
Add ability to increment progress bar without tracking the counter

### PR DESCRIPTION
**Pull request by fracz**
Issue https://github.com/guiguiboy/PHP-CLI-Progress-Bar/issues/1

### CODE REVIEW

**Comment by guiguiboy** [comment]
Hi,
thanks for this PR.
But I was wondering, is it woth the case throwing an Exception whenever the counter is greater than the max ?

**Comment by fracz** [comment]
It is an unexpected progress state for me if it reaches more than 100% - therefore I have added this check. However, if you consider it useless, I can recreate this PR without this check.

**Comment by guiguiboy** [comment]
Well, after re-reading my old code, I was already throwing Exceptions for inavlid values. So I believe we can continue this way.

**Comment by fracz** [comment]
Thank for the merge. I only noticed that I didn't change the version number on the top of Readme.md - should I create another PR for it or will you fix it?

**Comment by guiguiboy** [comment]
I will fix it. Thanks for reporting it.

**Pull request merged**
